/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.esta;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JPanel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author leandroleonperez
 */
public class Diseño extends javax.swing.JFrame {

    public Diseño() {
        initComponents();
        ingresar eO = new ingresar();
        //btn_retirar.setVisible(false);

        eO.setSize(1110, 460);
        eO.setLocation(0, 0);

        dinamico.removeAll();
        dinamico.add(eO, BorderLayout.CENTER);
        dinamico.revalidate();
        dinamico.repaint();
        cerrar();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        dinamico = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_retirar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_usuario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_consulta = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btn_rendimiento = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_tarifas = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dinamico.setBackground(new java.awt.Color(255, 255, 255));
        dinamico.setMinimumSize(new java.awt.Dimension(1200, 550));

        javax.swing.GroupLayout dinamicoLayout = new javax.swing.GroupLayout(dinamico);
        dinamico.setLayout(dinamicoLayout);
        dinamicoLayout.setHorizontalGroup(
            dinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        dinamicoLayout.setVerticalGroup(
            dinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        bg.add(dinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 1200, 550));

        sidepane.setBackground(new java.awt.Color(100, 189, 12));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_retirar.setBackground(new java.awt.Color(100, 189, 12));
        btn_retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_retirarMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/nochePension.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PENSIÓN POR NOCHE");

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("/ PÉRDIDA");

        javax.swing.GroupLayout btn_retirarLayout = new javax.swing.GroupLayout(btn_retirar);
        btn_retirar.setLayout(btn_retirarLayout);
        btn_retirarLayout.setHorizontalGroup(
            btn_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_retirarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(btn_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_retirarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel18))
                    .addGroup(btn_retirarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        btn_retirarLayout.setVerticalGroup(
            btn_retirarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(btn_retirarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidepane.add(btn_retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 250, 60));

        btn_ingresar.setBackground(new java.awt.Color(117, 222, 13));
        btn_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ingresarMousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/estacionamiento.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("INGRESAR VEHÍCULO");

        javax.swing.GroupLayout btn_ingresarLayout = new javax.swing.GroupLayout(btn_ingresar);
        btn_ingresar.setLayout(btn_ingresarLayout);
        btn_ingresarLayout.setHorizontalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_ingresarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btn_ingresarLayout.setVerticalGroup(
            btn_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ingresarLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_ingresarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 250, 60));

        btn_usuario.setBackground(new java.awt.Color(100, 189, 12));
        btn_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_usuarioMousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/grupo.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("USUARIOS");

        javax.swing.GroupLayout btn_usuarioLayout = new javax.swing.GroupLayout(btn_usuario);
        btn_usuario.setLayout(btn_usuarioLayout);
        btn_usuarioLayout.setHorizontalGroup(
            btn_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_usuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addGap(45, 45, 45)
                .addComponent(jLabel11)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        btn_usuarioLayout.setVerticalGroup(
            btn_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_usuarioLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_usuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(22, 22, 22))
        );

        sidepane.add(btn_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 60));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 5));
        sidepane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 250, 20));

        btn_consulta.setBackground(new java.awt.Color(100, 189, 12));
        btn_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_consultaMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/buscar.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CONSULTA");

        javax.swing.GroupLayout btn_consultaLayout = new javax.swing.GroupLayout(btn_consulta);
        btn_consulta.setLayout(btn_consultaLayout);
        btn_consultaLayout.setHorizontalGroup(
            btn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_consultaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        btn_consultaLayout.setVerticalGroup(
            btn_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_consultaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidepane.add(btn_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 250, 60));

        btn_rendimiento.setBackground(new java.awt.Color(100, 189, 12));
        btn_rendimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_rendimientoMousePressed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/alto-rendimiento.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("RENDIMIENTO");

        javax.swing.GroupLayout btn_rendimientoLayout = new javax.swing.GroupLayout(btn_rendimiento);
        btn_rendimiento.setLayout(btn_rendimientoLayout);
        btn_rendimientoLayout.setHorizontalGroup(
            btn_rendimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_rendimientoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel13)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btn_rendimientoLayout.setVerticalGroup(
            btn_rendimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_rendimientoLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_rendimientoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_rendimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 250, 60));

        btn_tarifas.setBackground(new java.awt.Color(100, 189, 12));
        btn_tarifas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_tarifasMousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cuota.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TARIFAS");

        javax.swing.GroupLayout btn_tarifasLayout = new javax.swing.GroupLayout(btn_tarifas);
        btn_tarifas.setLayout(btn_tarifasLayout);
        btn_tarifasLayout.setHorizontalGroup(
            btn_tarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_tarifasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel16)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        btn_tarifasLayout.setVerticalGroup(
            btn_tarifasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_tarifasLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btn_tarifasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_tarifas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 250, 60));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ADMINISTRADOR");
        sidepane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 190, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 640));

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ESTACIÓN 3");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("ESTACIONAMIENTO Y LAVA AUTO");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/carwash.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/marcador-de-posicion.png"))); // NOI18N

        cerrarSesion.setBackground(new java.awt.Color(0, 102, 204));
        cerrarSesion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        cerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesion.setText("CERRAR SESIÓN");
        cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(137, 137, 137)))
                .addComponent(jLabel4)
                .addGap(98, 98, 98)
                .addComponent(cerrarSesion)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1170, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void cerrar(){
        try{
           this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           this.addWindowListener(new WindowAdapter(){
               @Override
           public void windowClosing(WindowEvent e){
          String horaSalida;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        horaSalida = dateFormat.format(date);
        Login log = new Login();
        Connection cn;
        cn = Dconexion.getConnection();

        try {
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stat.executeUpdate("UPDATE checador SET horaSalida='" + horaSalida + "'order by idUsuario desc limit 1;");
        } catch (SQLException ex) {
            Logger.getLogger(Diseño.class.getName()).log(Level.SEVERE, null, ex);
        }

           }
           });
        }catch(Exception E){
             System.out.println(E);
        }
            
    }
    private void btn_ingresarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarMousePressed
        // TODO add your handling code here:
        ingresar eO = new ingresar();
        eO.setSize(1110, 460);
        eO.setLocation(0, 0);

        dinamico.removeAll();
        dinamico.add(eO, BorderLayout.CENTER);
        dinamico.revalidate();
        dinamico.repaint();

        setColor(btn_ingresar);
        getColor(btn_retirar);
        getColor(btn_consulta);
        getColor(btn_usuario);
        getColor(btn_rendimiento);
        getColor(btn_tarifas);
    }//GEN-LAST:event_btn_ingresarMousePressed

    private void btn_retirarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_retirarMousePressed
        // TODO add your handling code here:
        retirar cE = new retirar();
        cE.setSize(1110, 460);
        cE.setLocation(0, 0);

        dinamico.removeAll();
        dinamico.add(cE, BorderLayout.CENTER);
        dinamico.revalidate();
        dinamico.repaint();

        setColor(btn_retirar);
        getColor(btn_ingresar);
        getColor(btn_usuario);
        getColor(btn_consulta);
        getColor(btn_rendimiento);
        getColor(btn_tarifas);
    }//GEN-LAST:event_btn_retirarMousePressed

    private void btn_consultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultaMousePressed
        // TODO add your handling code here:
        consulta co = new consulta();
        co.setSize(1110, 460);
        co.setLocation(0, 0);

        dinamico.removeAll();
        dinamico.add(co, BorderLayout.CENTER);
        dinamico.revalidate();
        dinamico.repaint();

        setColor(btn_consulta);
        getColor(btn_ingresar);
        getColor(btn_retirar);
        getColor(btn_usuario);
        getColor(btn_rendimiento);
        getColor(btn_tarifas);
    }//GEN-LAST:event_btn_consultaMousePressed

    private void btn_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuarioMousePressed
        // TODO add your handling code here:
        usuarios co = new usuarios();
        co.setSize(1110, 460);
        co.setLocation(0, 0);

        dinamico.removeAll();
        dinamico.add(co, BorderLayout.CENTER);
        dinamico.revalidate();
        dinamico.repaint();

        setColor(btn_usuario);
        getColor(btn_ingresar);
        getColor(btn_retirar);
        getColor(btn_consulta);
        getColor(btn_rendimiento);
        getColor(btn_tarifas);
    }//GEN-LAST:event_btn_usuarioMousePressed

    private void btn_rendimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rendimientoMousePressed
        // TODO add your handling code here:
        reportesgrandes co = new reportesgrandes();
        co.setSize(1200, 550);
        co.setLocation(0, 0);

        dinamico.removeAll();
        dinamico.add(co,BorderLayout.CENTER);
        dinamico.revalidate();
        dinamico.repaint();
                
        
        setColor(btn_rendimiento);
        getColor(btn_ingresar);
        getColor(btn_retirar);
        getColor(btn_consulta);
        getColor(btn_usuario);
        getColor(btn_tarifas);
    }//GEN-LAST:event_btn_rendimientoMousePressed

    private void btn_tarifasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tarifasMousePressed
        // TODO add your handling code here:
        tarifas co = new tarifas();
        co.setSize(1110, 460);
        co.setLocation(0, 0);

        dinamico.removeAll();
        dinamico.add(co, BorderLayout.CENTER);
        dinamico.revalidate();
        dinamico.repaint();

        setColor(btn_tarifas);
        getColor(btn_ingresar);
        getColor(btn_retirar);
        getColor(btn_consulta);
        getColor(btn_usuario);
        getColor(btn_rendimiento);
    }//GEN-LAST:event_btn_tarifasMousePressed

    private void cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionActionPerformed
        String horaSalida;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Calendar cal = Calendar.getInstance();
        Date date = cal.getTime();
        horaSalida = dateFormat.format(date);
        Login log = new Login();
        Connection cn;
        cn = Dconexion.getConnection();

        try {
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stat.executeUpdate("UPDATE checador SET horaSalida='" + horaSalida + "'order by idUsuario desc limit 1;");
        } catch (SQLException ex) {
            Logger.getLogger(Diseño.class.getName()).log(Level.SEVERE, null, ex);
        }

        Login pr = new Login();
        pr.revalidate();
        pr.repaint();
        pr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionActionPerformed

//[51,153,0]color claro 
    void setColor(JPanel panel) {
        panel.setBackground(new Color(117, 222, 13));

    }
//[27,143,6]color fuerte 

    void getColor(JPanel panel) {
        panel.setBackground(new Color(100, 189, 12));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_consulta;
    private javax.swing.JPanel btn_ingresar;
    private javax.swing.JPanel btn_rendimiento;
    private javax.swing.JPanel btn_retirar;
    private javax.swing.JPanel btn_tarifas;
    private javax.swing.JPanel btn_usuario;
    private javax.swing.JButton cerrarSesion;
    private javax.swing.JPanel dinamico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
