/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esta;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Atxy2k.CustomTextField.RestrictedTextField;
import java.text.DecimalFormat;

/**
 *
 * @author Leandro
 */
public class retirar extends javax.swing.JPanel {
    double perdida=50.00;
    double valorAPagarTotal = 00.00;
    /**
     * Creates new form retirar
     */
    public retirar() {
        initComponents();
        RestrictedTextField r = new RestrictedTextField(tfPlaca);
        r.setLimit(7);
        //btn_retirar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        getEstAz = new javax.swing.JLabel();
        getEstAra = new javax.swing.JLabel();
        btn_retirar = new javax.swing.JButton();
        tfPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        horaEn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        horaSal = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        impo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tipoVe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnNoche = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        obser1 = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1110, 460));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel5.setText("PLACA/MATRÍCULA");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));
        bg.add(getEstAz, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 110, 20));
        bg.add(getEstAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, 110, 20));

        btn_retirar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btn_retirar.setText("RETIRAR");
        btn_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retirarActionPerformed(evt);
            }
        });
        bg.add(btn_retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 120, 40));

        tfPlaca.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tfPlaca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPlaca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlacaActionPerformed(evt);
            }
        });
        tfPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPlacaKeyTyped(evt);
            }
        });
        bg.add(tfPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 270, 70));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("ENTRADA");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        horaEn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        horaEn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horaEn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.add(horaEn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 170, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("SALIDA");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        horaSal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        horaSal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        horaSal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        horaSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaSalActionPerformed(evt);
            }
        });
        bg.add(horaSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 170, -1));

        marca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        marca.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        marca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });
        bg.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 170, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("MODELO");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("COLOR");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jLabel6.setText("IMPORTE: $");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, -1, -1));

        color.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        color.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        color.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 150, -1));

        buscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        bg.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 120, 40));

        impo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        impo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        impo.setText("0.00");
        impo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bg.add(impo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 100, 40));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("TIPO DE VEHÍCULO");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        tipoVe.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tipoVe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tipoVe.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.add(tipoVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 150, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("OBSERVACIONES");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        btnNoche.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnNoche.setText("PENSIÓN NOCHE");
        btnNoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNocheActionPerformed(evt);
            }
        });
        bg.add(btnNoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, 190, 40));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton1.setText("PÉRDIDA DEL BOLETO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 240, 40));

        obser1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        obser1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(obser1);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 160, 70));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setText("MARCA");
        bg.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        modelo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        modelo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bg.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    String consulta;
    PreparedStatement ps;
    ResultSet rs;
    double valorAPagarN = 00.00;
    String horasalida = "";
    
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    Calendar cal = Calendar.getInstance();
    Date date = cal.getTime();
    String fechaHora = dateFormat.format(date);

    private void btn_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retirarActionPerformed
        double valorAPagar = 00.00;
        ingresar ing = new ingresar();

        
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Statement stat1 = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            Statement stat2 = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat.executeQuery("SELECT horaEntrada, tipoV  FROM vehiculo WHERE placas='" + tfPlaca.getText() + "';");
            ResultSet rs1 = stat1.executeQuery("SELECT * FROM taries where idtarifaEsta = '1'");
            ResultSet rs2 = stat2.executeQuery("SELECT importe FROM vehiculo WHERE placas='" + tfPlaca.getText() + "';");

            rs.first();
            

            while (rs1.next()) {

                double cobro = (rs1.getDouble(2));
                String horaSalida = rs.getString(1);
                Date horasalida = dateFormat.parse(horaSalida);
                double minutosACobrar = (double) (date.getTime() - horasalida.getTime()) / 60000;
                valorAPagar = cobro * (minutosACobrar - minutosACobrar % 60) / 60;
                System.out.println(minutosACobrar);

                if (minutosACobrar % 60 != 0) {
                    if (rs.getString(2).equals("Automovil")) {
                        valorAPagar = valorAPagar + rs1.getDouble(2);
                    } else if (rs.getString(2).equals("Motocicleta")) {
                        valorAPagar = valorAPagar + rs1.getDouble(4);
                    } else if (rs.getString(2).equals("Camioneta")) {
                        valorAPagar = valorAPagar + rs1.getDouble(3);
                    }
                }
            }

            while (rs2.next()) {
                if (rs2.getDouble(1) < 700) {
                    valorAPagarTotal = valorAPagar + rs2.getDouble(1);
                }
            }

                System.out.println("Valor a pagar por estacionamiento" + rs.getString(2) + "= " + valorAPagar);
                stat.executeUpdate("UPDATE vehiculo SET importe='" + valorAPagarTotal + "',horaSalida='" + fechaHora + "' WHERE placas='" + tfPlaca.getText() + "'AND tipoServicio like 'Esta%';");
                JOptionPane.showMessageDialog(null, "VALOR A PAGAR TOTAL: $" + valorAPagarTotal);
            }catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "REVISE LOS DATOS NUEVAMENTE");
            Logger.getLogger(retirar.class.getName()).log(Level.SEVERE, null, ex);
        }catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "PLACAS NO ENCONTRADAS");
            Logger.getLogger(retirar.class.getName()).log(Level.SEVERE, null, ex);
        }
            DecimalFormat df = new DecimalFormat("#.00");
            impo.setText(String.valueOf(df.format(valorAPagarTotal)));
            //impo.setText("" + valorAPagarTotal );
            horaSal.setText("" + fechaHora);
    }//GEN-LAST:event_btn_retirarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat.executeQuery("SELECT * FROM vehiculo WHERE placas='" + tfPlaca.getText() + "'and tipoServicio like 'Esta%'  and horaSalida is null;");
            rs.first();
            this.horaEn.setText(rs.getString("horaEntrada"));  //campo 1 de la tabla personas
            this.horaSal.setText(rs.getString("horaSalida"));
            this.marca.setText(rs.getString("marca"));  //campo 1 de la tabla personas
            this.modelo.setText(rs.getString("modelo"));  //campo 1 de la tabla personas
            this.color.setText(rs.getString("color"));//campo 2 de la tabla personas
            this.tipoVe.setText(rs.getString("tipoV"));  //campo 1 de la tabla personas
            this.obser1.setText(rs.getString("obser"));  //campo 1 de la tabla personas
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "PLACAS NO ENCONTRADAS");        }
    }//GEN-LAST:event_buscarActionPerformed

    private void tfPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlacaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (Character.isLowerCase(caracter)) {
            evt.setKeyChar(Character.toUpperCase(caracter));

        }
    }//GEN-LAST:event_tfPlacaKeyTyped

    private void tfPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPlacaActionPerformed

    private void btnNocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNocheActionPerformed
        String servicioOp = "";
        try{
        Connection cn;
        cn = Dconexion.getConnection();
        Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
        Statement stat1 = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet rs1 = stat1.executeQuery("SELECT autoMe FROM taries WHERE idtarifaEsta=3");
        rs1.first();  
        servicioOp = "Pension por noche";
        valorAPagarN = (rs1.getDouble(1));
        JOptionPane.showMessageDialog(null, "VALOR A PAGAR: $" + valorAPagarN);
        stat.executeUpdate("UPDATE vehiculo SET importe='" + valorAPagarN + "',tipoServicio='" + servicioOp +  "',horaSalida='" + fechaHora + "' WHERE placas='" + tfPlaca.getText() + "';");
        } catch (Exception e) {
                System.out.println(e);
            }
        impo.setText("" + valorAPagarN);
        horaSal.setText("" + fechaHora);
    }//GEN-LAST:event_btnNocheActionPerformed

    private void horaSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaSalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            valorAPagarTotal= valorAPagarTotal+perdida;
            Connection cn;
            cn = Dconexion.getConnection();
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            stat.executeUpdate("UPDATE vehiculo SET importe='" + valorAPagarTotal+ "' WHERE placas='" + tfPlaca.getText() + "';");
        } catch (SQLException ex) {
            Logger.getLogger(retirar.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "VALOR A PAGAR: $" + valorAPagarTotal);
         impo.setText("" + valorAPagarTotal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnNoche;
    private javax.swing.JButton btn_retirar;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField color;
    private javax.swing.JLabel getEstAra;
    private javax.swing.JLabel getEstAz;
    private javax.swing.JTextField horaEn;
    private javax.swing.JTextField horaSal;
    private javax.swing.JTextField impo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextPane obser1;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tipoVe;
    // End of variables declaration//GEN-END:variables
}
