/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.esta;

import Atxy2k.CustomTextField.RestrictedTextField;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro
 */
public class tarifas extends javax.swing.JPanel {

    /**
     * Creates new form consulta
     */
    public tarifas() {
        initComponents();
        au.setVisible(false);
        ca.setVisible(false);
        mo.setVisible(false);
        a.setVisible(false);
        c.setVisible(false);
        x.setVisible(false);
        x1.setVisible(false);
        x2.setVisible(false);
        y.setVisible(false);
        y1.setVisible(false);
        y2.setVisible(false);
        y3.setVisible(false);
        z.setVisible(false);
        z1.setVisible(false);
        motocicletaEs.setVisible(false);
        
        ac.setVisible(false);
        am.setVisible(false);
        cala.setVisible(false);
        motola.setVisible(false);
        autochico.setVisible(false);
        automediano.setVisible(false);
        camionetala.setVisible(false);
        motocicletala.setVisible(false);
        
        pensionmen.setVisible(false);
        pensionmensual.setVisible(false);
        pensionpordia.setVisible(false);
        pensiondia.setVisible(false);
        
        btn_aceptar.setVisible(false);
        btn_aceptar2.setVisible(false);
        btn_aceptar3.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        getEstAz = new javax.swing.JLabel();
        getEstAra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        ca = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        au = new javax.swing.JLabel();
        motocicletaEs = new javax.swing.JTextField();
        mo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ac = new javax.swing.JLabel();
        autochico = new javax.swing.JTextField();
        cala = new javax.swing.JLabel();
        camionetala = new javax.swing.JTextField();
        motocicletala = new javax.swing.JTextField();
        motola = new javax.swing.JLabel();
        am = new javax.swing.JLabel();
        automediano = new javax.swing.JTextField();
        pensionmensual = new javax.swing.JLabel();
        pensionmen = new javax.swing.JTextField();
        pensiondia = new javax.swing.JTextField();
        pensionpordia = new javax.swing.JLabel();
        btn_pension = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_estacionamiento = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_lava = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btn_aceptar3 = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        btn_aceptar2 = new javax.swing.JButton();
        y3 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        x1 = new javax.swing.JLabel();
        x2 = new javax.swing.JLabel();
        z1 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        y2 = new javax.swing.JLabel();
        y = new javax.swing.JLabel();
        z = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1110, 460));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        bg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));
        bg.add(getEstAz, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 110, 20));
        bg.add(getEstAra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 400, 110, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setText("SELECCIONE EL SERVICIO");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 320, 30));

        c.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        c.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 50, -1));

        ca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ca.setText("CAMIONETA      $");
        bg.add(ca, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 20));

        a.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 50, -1));

        au.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        au.setText("AUTOMÓVIL      $");
        bg.add(au, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, 20));

        motocicletaEs.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        motocicletaEs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(motocicletaEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 50, -1));

        mo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        mo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mo.setText("MOTOCICLETA   $");
        bg.add(mo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 150, 20));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("PENSIÓN");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 90, 80, 30));

        ac.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ac.setText("AUTO CHICO           $");
        bg.add(ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 180, 20));

        autochico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        autochico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(autochico, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 60, -1));

        cala.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cala.setText("CAMIONETA            $");
        bg.add(cala, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 180, 20));

        camionetala.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        camionetala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(camionetala, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 60, -1));

        motocicletala.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        motocicletala.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(motocicletala, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 60, -1));

        motola.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        motola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        motola.setText("MOTOCICLETA        $");
        bg.add(motola, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 180, 20));

        am.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        am.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        am.setText("AUTO MEDIANO     $");
        bg.add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 180, 20));

        automediano.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        automediano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(automediano, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 60, -1));

        pensionmensual.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pensionmensual.setText("PENSIÓN MENSUAL   $");
        bg.add(pensionmensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 160, 20));

        pensionmen.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pensionmen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bg.add(pensionmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, 70, -1));

        pensiondia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pensiondia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pensiondia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pensiondiaActionPerformed(evt);
            }
        });
        bg.add(pensiondia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 70, -1));

        pensionpordia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        pensionpordia.setText("PENSIÓN POR DÍA     $");
        bg.add(pensionpordia, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 160, 20));

        btn_pension.setBackground(new java.awt.Color(204, 204, 204));
        btn_pension.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_pension.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_pensionMousePressed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/parking.png"))); // NOI18N

        javax.swing.GroupLayout btn_pensionLayout = new javax.swing.GroupLayout(btn_pension);
        btn_pension.setLayout(btn_pensionLayout);
        btn_pensionLayout.setHorizontalGroup(
            btn_pensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_pensionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(16, 16, 16))
        );
        btn_pensionLayout.setVerticalGroup(
            btn_pensionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_pensionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(39, 39, 39))
        );

        bg.add(btn_pension, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 120, 120));

        btn_estacionamiento.setBackground(new java.awt.Color(204, 204, 204));
        btn_estacionamiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_estacionamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_estacionamientoMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/estacionamiento-de-autos.png"))); // NOI18N

        javax.swing.GroupLayout btn_estacionamientoLayout = new javax.swing.GroupLayout(btn_estacionamiento);
        btn_estacionamiento.setLayout(btn_estacionamientoLayout);
        btn_estacionamientoLayout.setHorizontalGroup(
            btn_estacionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_estacionamientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btn_estacionamientoLayout.setVerticalGroup(
            btn_estacionamientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_estacionamientoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(39, 39, 39))
        );

        bg.add(btn_estacionamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 120, 120));

        btn_lava.setBackground(new java.awt.Color(204, 204, 204));
        btn_lava.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_lava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_lavaMousePressed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/wash.png"))); // NOI18N

        javax.swing.GroupLayout btn_lavaLayout = new javax.swing.GroupLayout(btn_lava);
        btn_lava.setLayout(btn_lavaLayout);
        btn_lavaLayout.setHorizontalGroup(
            btn_lavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_lavaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(16, 16, 16))
        );
        btn_lavaLayout.setVerticalGroup(
            btn_lavaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_lavaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(39, 39, 39))
        );

        bg.add(btn_lava, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 120, 120));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel13.setText("ESTACIONAMIENTO");
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, 30));

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel14.setText("LAVA AUTO");
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 90, 30));

        btn_aceptar3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_aceptar3.setText("ACEPTAR");
        btn_aceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar3ActionPerformed(evt);
            }
        });
        bg.add(btn_aceptar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 130, -1, -1));

        btn_aceptar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        bg.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        btn_aceptar2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_aceptar2.setText("ACEPTAR");
        btn_aceptar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar2ActionPerformed(evt);
            }
        });
        bg.add(btn_aceptar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        y3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        y3.setText("Hora y/o fracción");
        bg.add(y3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, 40));

        x.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        x.setText("Hora y/o fracción");
        bg.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, 40));

        x1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        x1.setText("Hora y/o fracción");
        bg.add(x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, 40));

        x2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        x2.setText("Hora y/o fracción");
        bg.add(x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, 40));

        z1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        z1.setText("Hora y/o fracción");
        bg.add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 320, -1, 40));

        y1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        y1.setText("Hora y/o fracción");
        bg.add(y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, -1, 40));

        y2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        y2.setText("Hora y/o fracción");
        bg.add(y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, 40));

        y.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        y.setText("Hora y/o fracción");
        bg.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, -1, 30));

        z.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        z.setText("Hora y/o fracción");
        bg.add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_estacionamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_estacionamientoMousePressed
        // TODO add your handling code here:
        au.setVisible(true);
        ca.setVisible(true);
        mo.setVisible(true);
        a.setVisible(true);
        c.setVisible(true);
        x.setVisible(true);
        x1.setVisible(true);
        x2.setVisible(true);
        y.setVisible(false);
        y1.setVisible(false);
        y2.setVisible(false);
        y3.setVisible(false);
        z.setVisible(false);
        z1.setVisible(false);
        motocicletaEs.setVisible(true);
        btn_aceptar.setVisible(true);
        btn_aceptar2.setVisible(false);
        btn_aceptar3.setVisible(false);
        
        ac.setVisible(false);
        am.setVisible(false);
        cala.setVisible(false);
        motola.setVisible(false);
        autochico.setVisible(false);
        automediano.setVisible(false);
        camionetala.setVisible(false);
        motocicletala.setVisible(false);
        
        pensionmen.setVisible(false);
        pensiondia.setVisible(false);
        pensionmensual.setVisible(false);
        pensionpordia.setVisible(false);

        //
        PreparedStatement ps;
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat.executeQuery("SELECT * FROM taries WHERE idtarifaEsta=1 ;");
            if (rs.first()) {
                this.a.setText(rs.getString("auto"));
                this.c.setText(rs.getString("camioneta"));
                this.motocicletaEs.setText(rs.getString("moto"));
                
            } else {
                JOptionPane.showMessageDialog(null, "NO SE ENCUENTRA EL USUARIO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setColor(btn_estacionamiento);
        getColor(btn_lava);
        getColor(btn_pension);
    }//GEN-LAST:event_btn_estacionamientoMousePressed

    private void btn_lavaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lavaMousePressed
        // TODO add your handling code here:
        //ESTACIONAMIENTO
        btn_aceptar.setVisible(false);
        btn_aceptar3.setVisible(false);
        btn_aceptar2.setVisible(true);
        au.setVisible(false);
        ca.setVisible(false);
        mo.setVisible(false);
        a.setVisible(false);
        c.setVisible(false);
        x.setVisible(false);
        x1.setVisible(false);
        x2.setVisible(false);
        y.setVisible(true);
        y1.setVisible(true);
        y2.setVisible(true);
        y3.setVisible(false);
        z.setVisible(false);
        z1.setVisible(false);
        motocicletaEs.setVisible(false);
        //LAVA AUTO
        ac.setVisible(true);
        am.setVisible(true);
        cala.setVisible(true);
        motola.setVisible(true);
        autochico.setVisible(true);
        automediano.setVisible(true);
        camionetala.setVisible(true);
        motocicletala.setVisible(true);
        //PENSION
        pensionmen.setVisible(false);
        pensionmensual.setVisible(false);
        pensionpordia.setVisible(false);
        pensiondia.setVisible(false);
        
        PreparedStatement ps;
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat.executeQuery("SELECT * FROM taries WHERE idtarifaEsta=2 ;");
            if (rs.first()) {
                this.autochico.setText(rs.getString("auto"));
                this.automediano.setText(rs.getString("autoMe"));
                this.camionetala.setText(rs.getString("camioneta"));
                this.motocicletala.setText(rs.getString("moto"));
                
            } else {
                JOptionPane.showMessageDialog(null, "NO SE ENCUENTRA EL USUARIO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        setColor(btn_lava);
        getColor(btn_estacionamiento);
        getColor(btn_pension);
    }//GEN-LAST:event_btn_lavaMousePressed

    private void btn_pensionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pensionMousePressed
        // TODO add your handling code here:
        //ESTACIONAMIENTO
        btn_aceptar3.setVisible(true);
        btn_aceptar.setVisible(false);
        btn_aceptar2.setVisible(false);
        au.setVisible(false);
        ca.setVisible(false);
        mo.setVisible(false);
        a.setVisible(false);
        c.setVisible(false);
        x.setVisible(false);
        x1.setVisible(false);
        x2.setVisible(false);
        y.setVisible(false);
        y1.setVisible(false);
        y2.setVisible(false);
        y3.setVisible(false);
        z.setVisible(true);
        z1.setVisible(true);
        motocicletaEs.setVisible(false);
        //LAVA AUTO
        ac.setVisible(false);
        am.setVisible(false);
        cala.setVisible(false);
        motola.setVisible(false);
        autochico.setVisible(false);
        automediano.setVisible(false);
        camionetala.setVisible(false);
        motocicletala.setVisible(false);
        //PENSION
        pensionmen.setVisible(true);
        pensionmensual.setVisible(true);
        pensionpordia.setVisible(true);
        pensiondia.setVisible(true);
        
        PreparedStatement ps;
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stat.executeQuery("SELECT * FROM taries WHERE idtarifaEsta=3 ;");
            if (rs.first()) {
                this.pensionmen.setText(rs.getString("auto"));
                this.pensiondia.setText(rs.getString("autoMe"));
                
            } else {
                JOptionPane.showMessageDialog(null, "NO SE ENCUENTRA EL USUARIO");
            }
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        setColor(btn_pension);
        getColor(btn_lava);
        getColor(btn_estacionamiento);
    }//GEN-LAST:event_btn_pensionMousePressed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            //Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ps = cn.prepareStatement("UPDATE taries SET auto=?, camioneta=?, moto=?  WHERE idtarifaEsta= 1 ;");
            ps.setString(1, a.getText());
            ps.setString(2, c.getText());
            ps.setString(3, motocicletaEs.getText());
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "TARIFA ACTUALIZADA CORRECTAMENTE");
                a.setText("");
                c.setText("");
                motocicletaEs.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR");
            }
            cn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_aceptar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar2ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            //Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ps = cn.prepareStatement("UPDATE taries SET auto=?,autoMe=?, camioneta=?, moto=?  WHERE idtarifaEsta= 2 ;");
            ps.setString(1, autochico.getText());
            ps.setString(2, automediano.getText());
            ps.setString(3, camionetala.getText());
            ps.setString(4, motocicletala.getText());
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "TARIFA ACTUALIZADA CORRECTAMENTE");
                a.setText("");
                c.setText("");
                motocicletaEs.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR");
            }
            cn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_aceptar2ActionPerformed

    private void btn_aceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar3ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        try {
            Connection cn;
            cn = Dconexion.getConnection();
            //Statement stat = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ps = cn.prepareStatement("UPDATE taries SET auto=?,camioneta=?, moto=?, autoMe=?  WHERE idtarifaEsta= 3 ;");
            ps.setString(1, pensionmen.getText());
            ps.setString(2, pensionmen.getText());
            ps.setString(3, pensionmen.getText());
            ps.setString(4, pensiondia.getText());
            int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "TARIFA ACTUALIZADA CORRECTAMENTE");
                a.setText("");
                c.setText("");
                motocicletaEs.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR");
            }
            cn.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_aceptar3ActionPerformed

    private void pensiondiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pensiondiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pensiondiaActionPerformed

//[51,153,0]color claro 
    void setColor(JPanel panel
    ) {
        panel.setBackground(new Color(64, 64, 64));
        
    }
//[27,143,6]color fuerte 

    void getColor(JPanel panel
    ) {
        panel.setBackground(new Color(192, 192, 192));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JLabel ac;
    private javax.swing.JLabel am;
    private javax.swing.JLabel au;
    private javax.swing.JTextField autochico;
    private javax.swing.JTextField automediano;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_aceptar2;
    private javax.swing.JButton btn_aceptar3;
    private javax.swing.JPanel btn_estacionamiento;
    private javax.swing.JPanel btn_lava;
    private javax.swing.JPanel btn_pension;
    private javax.swing.JTextField c;
    private javax.swing.JLabel ca;
    private javax.swing.JLabel cala;
    private javax.swing.JTextField camionetala;
    private javax.swing.JLabel getEstAra;
    private javax.swing.JLabel getEstAz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mo;
    private javax.swing.JTextField motocicletaEs;
    private javax.swing.JTextField motocicletala;
    private javax.swing.JLabel motola;
    private javax.swing.JTextField pensiondia;
    private javax.swing.JTextField pensionmen;
    private javax.swing.JLabel pensionmensual;
    private javax.swing.JLabel pensionpordia;
    private javax.swing.JLabel x;
    private javax.swing.JLabel x1;
    private javax.swing.JLabel x2;
    private javax.swing.JLabel y;
    private javax.swing.JLabel y1;
    private javax.swing.JLabel y2;
    private javax.swing.JLabel y3;
    private javax.swing.JLabel z;
    private javax.swing.JLabel z1;
    // End of variables declaration//GEN-END:variables
}
